title: Kezhao Zhang
author: Kezhao Zhang 
email: kezhao.zhang@gmail.com
description: Learnng and practicing data analysis, machine learning, Bayesian inference and causal inference.

# social links
#twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
#github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima

highlighter: rouge
